#!/bin/bash

BASE_DIR=$(dirname $0)

git_config() {
    echo "Configuring git"
    git config --global core.editor vim
    git config --global core.excludesfile ~/.gitignore

    git config --global color.branch auto
    git config --global color.diff auto
    git config --global color.interactive auto
    git config --global color.status auto
    git config --global color.ui auto

    git config --global push.default simple

    if [[ "$GIT_USER_NAME" ]]; then
        git config --global user.name "$GIT_USER_NAME"
    fi

    if [[ "$GIT_USER_EMAIL" ]]; then
        git config --global user.email "$GIT_USER_EMAIL"
    fi
}

# Config install and uninstall script
if [[ "install" == $1 ]]; then
    echo "Installing dot configuration files"
    cp -frv ${BASE_DIR}/sbt ~/.sbt
    cp -frv ${BASE_DIR}/subversion ~/.subversion
    cp -frv ${BASE_DIR}/vim ~/.vim
    cp -frv ${BASE_DIR}/zsh ~/.zsh
    cp -v ${BASE_DIR}/bashrc ~/.bashrc
    cp -v ${BASE_DIR}/gitignore ~/.gitignore
    cp -v ${BASE_DIR}/tmux.conf ~/.tmux.conf
    cp -v ${BASE_DIR}/vimrc ~/.vimrc
    cp -v ${BASE_DIR}/zshrc ~/.zshrc

    echo "Installing Antigen"
    rm -fr ~/.antigen
    git clone https://github.com/zsh-users/antigen.git ~/.antigen

    echo "Installing Vundle"
    rm -fr ~/.vim/bundle/Vundle.vim
    git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim

    git_config
elif [[ "uninstall" == $1 ]]; then
    echo "Uninstalling dot configuration files"
    rm -fr ~/.sbt
    rm -fr ~/.subversion
    rm -fr ~/.vim
    rm -fr ~/.zsh
    rm ~/.bashrc
    rm ~/.gitignore
    rm ~/.tmux.conf
    rm ~/.vimrc
    rm ~/.zshrc

    echo "Uninstalling Antigen"
    rm -fr ~/.antigen

    echo "Uninstalling Vundle"
    rm -fr ~/.vim/bundle/Vundle.vim
elif [[ "git" == $1 ]]; then
    git_config
else
    echo "Usage: config install/uninstall"
fi
