#!/bin/bash

BASE_DIR=$(dirname $0)

git_config() {
    echo "Configuring git"
    git config --global core.editor vim
    git config --global core.excludesfile ${HOME}/.gitignore

    git config --global color.branch auto
    git config --global color.diff auto
    git config --global color.interactive auto
    git config --global color.status auto
    git config --global color.ui auto

    git config --global push.default simple
    git config --global pull.ff only
    git config --global alias.co checkout
    git config --global alias.cob 'checkout -b'
    git config --global alias.up '!git remote update -p; git merge --ff-only @{u}'

    if [[ "$GIT_USER_NAME" ]]; then
        git config --global user.name "$GIT_USER_NAME"
    fi

    if [[ "$GIT_USER_EMAIL" ]]; then
        git config --global user.email "$GIT_USER_EMAIL"
    fi
}

# Config install and uninstall script
if [[ "install" == $1 ]]; then
    echo "Installing dot configuration files"
    cp -frv ${BASE_DIR}/sbt ${HOME}/.sbt
    cp -frv ${BASE_DIR}/subversion ${HOME}/.subversion
    cp -frv ${BASE_DIR}/vim ${HOME}/.vim
    cp -frv ${BASE_DIR}/zsh ${HOME}/.zsh
    cp -v ${BASE_DIR}/bashrc ${HOME}/.bashrc
    cp -v ${BASE_DIR}/gitignore ${HOME}/.gitignore
    cp -v ${BASE_DIR}/tmux.conf ${HOME}/.tmux.conf
    cp -v ${BASE_DIR}/vimrc ${HOME}/.vimrc
    cp -v ${BASE_DIR}/zshrc ${HOME}/.zshrc

    echo "Installing Antigen"
    rm -fr ${HOME}/.antigen
    git clone https://github.com/zsh-users/antigen.git ${HOME}/.antigen

    echo "Installing Vundle"
    rm -fr ${HOME}/.vim/bundle/Vundle.vim
    git clone https://github.com/gmarik/Vundle.vim.git ${HOME}/.vim/bundle/Vundle.vim

    git_config
elif [[ "uninstall" == $1 ]]; then
    echo "Uninstalling dot configuration files"
    rm -fr ${HOME}/.sbt
    rm -fr ${HOME}/.subversion
    rm -fr ${HOME}/.vim
    rm -fr ${HOME}/.zsh
    rm ${HOME}/.bashrc
    rm ${HOME}/.gitignore
    rm ${HOME}/.tmux.conf
    rm ${HOME}/.vimrc
    rm ${HOME}/.zshrc

    echo "Uninstalling Antigen"
    rm -fr ${HOME}/.antigen

    echo "Uninstalling Vundle"
    rm -fr ${HOME}/.vim/bundle/Vundle.vim
elif [[ "git" == $1 ]]; then
    git_config
else
    echo "Usage: config install/uninstall"
fi
