//credentials += Credentials(Path.userHome / ".sbt" / ".credentials")

//addSbtPlugin("com.eed3si9n" % "sbt-dirty-money" % "0.1.0")
//addSbtPlugin("com.eed3si9n" % "sbt-man" % "0.1.1")
addSbtPlugin("com.eed3si9n" % "sbt-sh" % "0.1.0")
addSbtPlugin("com.github.alexarchambault" %% "sbt-notebook" % "0.1.1")
addSbtPlugin("com.github.jozic" % "sbt-about-plugins" % "0.1.0")
//addSbtPlugin("com.github.mpeltonen" % "sbt-idea" % "1.6.0")
addSbtPlugin("com.orrsella" % "sbt-stats" % "1.0.5")
addSbtPlugin("com.sksamuel.sbt-versions" % "sbt-versions" % "0.2.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-git" % "0.8.5")
addSbtPlugin("com.timushev.sbt" % "sbt-updates" % "0.2.0")
//addSbtPlugin("io.scalac" % "sbt-process-runner" % "0.8.1")
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.8.2")
addSbtPlugin("com.gilt" % "sbt-dependency-graph-sugar" % "0.7.5-1")
